Jn photogram industrial 2
jniewiel/photogram-industrial pull request #2
Opened 2024-06-30 17:15 UTC by jniewiel

2024-06-30 19:53 UTC, aborov approved these changes
Looks good!

2024-07-01 16:18 UTC, thierrychau requested changes
Please see below comments

2024-07-01 16:18 UTC, thierrychau commented on app/models/comment.rb
> +  belongs_to :author, class_name: "User"
Can you add a counter_cache?

2024-07-01 16:18 UTC, thierrychau commented on app/models/comment.rb
> +  belongs_to :photo
Can you add a counter_cache?

2024-07-01 16:18 UTC, thierrychau commented on app/models/like.rb
> +  belongs_to :photo, counter_cache: true
Can you add a validation to make sure a user is not able to like the same photo more than once?

2024-07-01 16:45 UTC, thierrychau approved these changes
Looks great, good to merge.

2024-07-01 16:50 UTC, merged